# Colors
background #151218
foreground #E7E0E8
selection_background #503D74
selection_foreground #E7E0E8

# Cursor
cursor #D3BCFD
cursor_text_color #151218

# Normal colors
color0 #151218
color1 #F0B7C5
color2 #9688AE
color3 #F0B7C5
color4 #D3BCFD
color5 #CDC2DB
color6 #F0B7C5
color7 #E7E0E8

# Bright colors
color8 #49454E
color9 #F0B7C5
color10 #D3BCFD
color11 #CDC2DB
color12 #D3BCFD
color13 #9688AE
color14 #F0B7C5
color15 #E7E0E8

# Font
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 11.0
cursor_shape beam

# Window
window_padding_width 8
background_opacity 0.85
