general {
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/paulblart/Downloads/lock-wallpaper-edit.png
    blur_passes = 0
}

label {
    monitor =
    text = cmd[update:1000] date +"%I:%M %p"
    font_family = Calvin and Hobbes
    font_size = 80
    color = rgb(ffffff)
    position = -60, 120
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    font_family = Calvin and Hobbes
    font_size = 30
    color = rgb(ffffff)
    position = -60, 80
    halign = right
    valign = bottom
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    outer_color = rgb(d3bcfd)
    inner_color = rgb(151218)
    font_color = rgb(e7e0e8)
    check_color = rgb(f0b7c5)
    fail_color = rgb(cf6679)
    placeholder_text = password
    position = -60, 40
    halign = right
    valign = bottom
}
