monitor=,preferred,auto,1
monitor=HDMI-A-1,disabled

exec-once=gsettings set org.gnome.desktop.interface color-scheme prefer-dark
exec-once=hyprpaper
exec-once=waybar
exec-once=sleep 1 && hyprctl hyprpaper preload "/home/paulblart/Downloads/Lake-Hylia.jpg"
exec-once=sleep 2 && hyprctl hyprpaper wallpaper "eDP-1,/home/paulblart/Downloads/Lake-Hylia.jpg"

input {
	kb_layout=us
	follow_mouse=1
	touchpad {
		natural_scroll=yes
	}
}

general {
	gaps_in=3
	gaps_out=6
	border_size=2
	col.active_border=rgba(D3BCFDff)
	col.inactive_border=rgba(49454Eaa)
	layout=dwindle
}

decoration {
	rounding=10
	blur {
		enabled=true
		size=6
		passes=2
	}

	shadow {
		 enabled=true
		 range=12
		 render_power=3
	}
}

animations {
	enabled=yes

    bezier = ease,0.25,0.1,0.25,1

    animation = windows,1,5,ease,slide
    animation = windowsOut,1,5,ease,slide
    animation = border,1,5,ease
    animation = fade,1,5,ease
    animation = workspaces,1,6,ease,slide

}

dwindle {
	pseudotile=yes
	preserve_split=yes
}

# --- Basic Hotkeys ---
bind=SUPER,Return,exec,kitty
bind=SUPER,Q,killactive
bind=SUPER,M,exit
bind=SUPER,SPACE,exec,wofi --show drun
bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5


# ---  Volume F3 and F4 ---
bind=,XF86AudioRaiseVolume,exec,pactl set-sink-volume @DEFAULT_SINK@ +5%
bind=,XF86AudioLowerVolume,exec,pactl set-sink-volume @DEFAULT_SINK@ -5%
bind=,XF86AudioMute,exec,pactl set-sink-mute @DEFAULT_SINK@ toggle

# --- Brightness F4 and F5 ---
bind=,XF86MonBrightnessUp,exec,brightnessctl set +10%
bind=,XF86MonBrightnessDown,exec,brightnessctl set 10%-

# Screenshots - save to file
bind=,Print,exec,hyprshot -m output
bind=SUPER,Print,exec,hyprshot -m region

# Screenshots - copy to clipboard
bind=ALT,Print,exec,hyprshot -m output --clipboard-only
bind=CTRL,Print,exec,hyprshot -m region --clipboard-only

# Window focus
bind=SUPER,left,movefocus,l
bind=SUPER,right,movefocus,r
bind=SUPER,up,movefocus,u
bind=SUPER,down,movefocus,d

# Move windows around
bind=SUPERSHIFT,left,movewindow,l
bind=SUPERSHIFT,right,movewindow,r
bind=SUPERSHIFT,up,movewindow,u
bind=SUPERSHIFT,down,movewindow,d

# Resize windows
bind=SUPERALT,right,resizeactive,30 0
bind=SUPERALT,left,resizeactive,-30 0
bind=SUPERALT,up,resizeactive,0 -30
bind=SUPERALT,down,resizeactive,0 30

# Move workspaces with mouse scroll
bind=SUPER,mouse_down,workspace,e+1
bind=SUPER,mouse_up,workspace,e-1

# Float a window
bind=SUPERSHIFT,space,togglefloating

# Move floating windows with mouse
bindm=SUPER,mouse:272,movewindow
bindm=SUPER,mouse:273,resizewindow

# Lock screen
bind=SUPER,L,exec,hyprlock

# Maximize window
bind=SUPER,F,fullscreen,0
bind=SUPERSHIFT,F,fullscreen,1
